[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0", "wheel"]

[project]
authors = [{name = "Aditya Telange"}]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = []
description = "Patch an APK to disable network security configuration and bypass SSL pinning."
keywords = ["apk", "patch", "android", "netsec"]
license = {text = "MIT"}
name = "patch-netsec-conf"
readme = "README.md"
requires-python = ">=3.9"
version = "0.1.0"

[project.scripts]
patch-netsec-conf = "patch_netsec_conf.patch_netsec_conf:main"

[tool.setuptools]
include-package-data = true
packages = ["patch_netsec_conf"]

[tool.setuptools.package-dir]
patch_netsec_conf = "patch-netsec-conf"

[tool.setuptools.package-data]
patch_netsec_conf = ["network_security_config.xml", "network_security_config_plain.xml"]
